//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedProgramming_Lesson4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvancedProgramming_Lesson4.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string _for {
            get {
                return ResourceManager.GetString("for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string Access_denied {
            get {
                return ResourceManager.GetString("Access denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account..
        /// </summary>
        public static string account_ {
            get {
                return ResourceManager.GetString("account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another service to log in..
        /// </summary>
        public static string Add_another_service_to_log_in_ {
            get {
                return ResourceManager.GetString("Add another service to log in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        public static string Add_authenticator_app {
            get {
                return ResourceManager.GetString("Add authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming_Lesson4.
        /// </summary>
        public static string AdvancedProgramming_Lesson4 {
            get {
                return ResourceManager.GetString("AdvancedProgramming_Lesson4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string An_error_occurred_while_processing_your_request_ {
            get {
                return ResourceManager.GetString("An error occurred while processing your request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and restarting the application..
        /// </summary>
        public static string and_restarting_the_application_ {
            get {
                return ResourceManager.GetString("and restarting the application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_this_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the.
        /// </summary>
        public static string as_it_can_result_in_sensitive_information_from_exceptions_being_displayed_to_end_users__For_local_debugging__development_environment_can_be_enabled_by_setting_the {
            get {
                return ResourceManager.GetString("as it can result in sensitive information from exceptions being displayed to end " +
                        "users. For local debugging, development environment can be enabled by setting th" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your.
        /// </summary>
        public static string Associate_your {
            get {
                return ResourceManager.GetString("Associate your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        public static string Authors_ {
            get {
                return ResourceManager.GetString("Authors:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before you can log in with a recovery code..
        /// </summary>
        public static string before_you_can_log_in_with_a_recovery_code_ {
            get {
                return ResourceManager.GetString("before you can log in with a recovery code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to building Web apps with ASP.NET Core.
        /// </summary>
        public static string building_Web_apps_with_ASP_NET_Core {
            get {
                return ResourceManager.GetString("building Web apps with ASP.NET Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        public static string Change_email {
            get {
                return ResourceManager.GetString("Change email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string Change_your_account_settings {
            get {
                return ResourceManager.GetString("Change your account settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChatMessage.
        /// </summary>
        public static string ChatMessage {
            get {
                return ResourceManager.GetString("ChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to confirm your account.
        /// </summary>
        public static string Click_here_to_confirm_your_account {
            get {
                return ResourceManager.GetString("Click here to confirm your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string click_here_to_log_in {
            get {
                return ResourceManager.GetString("click here to log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        public static string Configure_authenticator_app {
            get {
                return ResourceManager.GetString("Configure authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string Confirm_email {
            get {
                return ResourceManager.GetString("Confirm email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email change.
        /// </summary>
        public static string Confirm_email_change {
            get {
                return ResourceManager.GetString("Confirm email change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create a new account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        public static string Delete_data_and_close_my_account {
            get {
                return ResourceManager.GetString("Delete data and close my account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Personal Data.
        /// </summary>
        public static string Delete_Personal_Data {
            get {
                return ResourceManager.GetString("Delete Personal Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string Deleting_this_data_will_permanently_remove_your_account__and_this_cannot_be_recovered_ {
            get {
                return ResourceManager.GetString("Deleting this data will permanently remove your account, and this cannot be recov" +
                        "ered.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development environment should not be enabled in deployed applications.
        /// </summary>
        public static string Development_environment_should_not_be_enabled_in_deployed_applications {
            get {
                return ResourceManager.GetString("Development environment should not be enabled in deployed applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        public static string Development_Mode {
            get {
                return ResourceManager.GetString("Development Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Disable_2FA {
            get {
                return ResourceManager.GetString("Disable 2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication (2FA).
        /// </summary>
        public static string Disable_two_factor_authentication__2FA_ {
            get {
                return ResourceManager.GetString("Disable two-factor authentication (2FA)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the keyused in an authenticator app you should.
        /// </summary>
        public static string Disabling_2FA_does_not_change_the_keys_used_in_authenticator_apps__If_you_wish_to_change_the_keyused_in_an_authenticator_app_you_should {
            get {
                return ResourceManager.GetString("Disabling 2FA does not change the keys used in authenticator apps. If you wish to" +
                        " change the keyused in an authenticator app you should", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to your authenticator device? You can.
        /// </summary>
        public static string Don_t_have_access_to_your_authenticator_device__You_can {
            get {
                return ResourceManager.GetString("Don\'t have access to your authenticator device? You can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Microsoft Authenticator for.
        /// </summary>
        public static string Download_a_two_factor_authenticator_app_like_Microsoft_Authenticator_for {
            get {
                return ResourceManager.GetString("Download a two-factor authenticator app like Microsoft Authenticator for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Your Data.
        /// </summary>
        public static string Download_Your_Data {
            get {
                return ResourceManager.GetString("Download Your Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable QR code generation.
        /// </summary>
        public static string enable_QR_code_generation {
            get {
                return ResourceManager.GetString("enable QR code generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string Enter_your_email_ {
            get {
                return ResourceManager.GetString("Enter your email.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment variable to.
        /// </summary>
        public static string environment_variable_to {
            get {
                return ResourceManager.GetString("environment variable to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to environment will display more detailed information about the error that occurred..
        /// </summary>
        public static string environment_will_display_more_detailed_information_about_the_error_that_occurred_ {
            get {
                return ResourceManager.GetString("environment will display more detailed information about the error that occurred." +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        public static string External_logins {
            get {
                return ResourceManager.GetString("External logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string for_details_on_setting_up_this_ASP_NET_application_to_support_logging_in_via_external_services_ {
            get {
                return ResourceManager.GetString("for details on setting up this ASP.NET application to support logging in via exte" +
                        "rnal services.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for how to configure a real email sender..
        /// </summary>
        public static string for_how_to_configure_a_real_email_sender_ {
            get {
                return ResourceManager.GetString("for how to configure a real email sender.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        public static string Forget_this_browser {
            get {
                return ResourceManager.GetString("Forget this browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string Forgot_password_confirmation {
            get {
                return ResourceManager.GetString("Forgot password confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_your_password_ {
            get {
                return ResourceManager.GetString("Forgot your password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate a new set of recovery codes.
        /// </summary>
        public static string generate_a_new_set_of_recovery_codes {
            get {
                return ResourceManager.GetString("generate a new set of recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Recovery Codes.
        /// </summary>
        public static string Generate_Recovery_Codes {
            get {
                return ResourceManager.GetString("Generate Recovery Codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate two-factor authentication (2FA) recovery codes.
        /// </summary>
        public static string Generate_two_factor_authentication__2FA__recovery_codes {
            get {
                return ResourceManager.GetString("Generate two-factor authentication (2FA) recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should.
        /// </summary>
        public static string Generating_new_recovery_codes_does_not_change_the_keys_used_in_authenticator_apps__If_you_wish_to_change_the_key_used_in_an_authenticator_app_you_should {
            get {
                return ResourceManager.GetString("Generating new recovery codes does not change the keys used in authenticator apps" +
                        ". If you wish to change the key used in an authenticator app you should", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string If_you_lose_your_device_and_don_t_have_the_recovery_codes_you_will_lose_access_to_your_account_ {
            get {
                return ResourceManager.GetString("If you lose your device and don\'t have the recovery codes you will lose access to" +
                        " your account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset your authenticator key your authenticator app will not work until you reconfigure it..
        /// </summary>
        public static string If_you_reset_your_authenticator_key_your_authenticator_app_will_not_work_until_you_reconfigure_it_ {
            get {
                return ResourceManager.GetString("If you reset your authenticator key your authenticator app will not work until yo" +
                        "u reconfigure it.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input password.
        /// </summary>
        public static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string into_your_two_factor_authenticator_app__Spaces_and_casing_do_not_matter_ {
            get {
                return ResourceManager.GetString("into your two factor authenticator app. Spaces and casing do not matter.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about.
        /// </summary>
        public static string Learn_about {
            get {
                return ResourceManager.GetString("Learn about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to.
        /// </summary>
        public static string Learn_how_to {
            get {
                return ResourceManager.GetString("Learn how to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string Locked_out {
            get {
                return ResourceManager.GetString("Locked out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in with a recovery code.
        /// </summary>
        public static string log_in_with_a_recovery_code {
            get {
                return ResourceManager.GetString("log in with a recovery code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Email.
        /// </summary>
        public static string Manage_Email {
            get {
                return ResourceManager.GetString("Manage Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string Manage_your_account {
            get {
                return ResourceManager.GetString("Manage your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string Manage_your_external_logins {
            get {
                return ResourceManager.GetString("Manage your external logins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageCreate.
        /// </summary>
        public static string MessageCreate {
            get {
                return ResourceManager.GetString("MessageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageDelete.
        /// </summary>
        public static string MessageDelete {
            get {
                return ResourceManager.GetString("MessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageEdit.
        /// </summary>
        public static string MessageEdit {
            get {
                return ResourceManager.GetString("MessageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageHub.
        /// </summary>
        public static string MessageHub {
            get {
                return ResourceManager.GetString("MessageHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normally this would be emailed:.
        /// </summary>
        public static string Normally_this_would_be_emailed_ {
            get {
                return ResourceManager.GetString("Normally this would be emailed:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will provide youwith a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string Once_you_have_scanned_the_QR_code_or_input_the_key_above__your_two_factor_authentication_app_will_provide_youwith_a_unique_code__Enter_the_code_in_the_confirmation_box_below_ {
            get {
                return ResourceManager.GetString("Once you have scanned the QR code or input the key above, your two factor authent" +
                        "ication app will provide youwith a unique code. Enter the code in the confirmati" +
                        "on box below.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string Personal_data {
            get {
                return ResourceManager.GetString("Personal data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to confirm your account..
        /// </summary>
        public static string Please_check_your_email_to_confirm_your_account_ {
            get {
                return ResourceManager.GetString("Please check your email to confirm your account.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string Please_check_your_email_to_reset_your_password_ {
            get {
                return ResourceManager.GetString("Please check your email to reset your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address for this site below and click the Register button to finishlogging in..
        /// </summary>
        public static string Please_enter_an_email_address_for_this_site_below_and_click_the_Register_button_to_finishlogging_in_ {
            get {
                return ResourceManager.GetString("Please enter an email address for this site below and click the Register button t" +
                        "o finishlogging in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put these codes in a safe place..
        /// </summary>
        public static string Put_these_codes_in_a_safe_place_ {
            get {
                return ResourceManager.GetString("Put these codes in a safe place.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code verification.
        /// </summary>
        public static string Recovery_code_verification {
            get {
                return ResourceManager.GetString("Recovery code verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes.
        /// </summary>
        public static string Recovery_codes {
            get {
                return ResourceManager.GetString("Recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecoveryCode.
        /// </summary>
        public static string RecoveryCode {
            get {
                return ResourceManager.GetString("RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string Register_as_a_new_user {
            get {
                return ResourceManager.GetString("Register as a new user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register confirmation.
        /// </summary>
        public static string Register_confirmation {
            get {
                return ResourceManager.GetString("Register confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered users.
        /// </summary>
        public static string Registered_users {
            get {
                return ResourceManager.GetString("Registered users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID:.
        /// </summary>
        public static string Request_ID_ {
            get {
                return ResourceManager.GetString("Request ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        public static string Reset_authenticator_app {
            get {
                return ResourceManager.GetString("Reset authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string Reset_authenticator_key {
            get {
                return ResourceManager.GetString("Reset authenticator key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Reset_password {
            get {
                return ResourceManager.GetString("Reset password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string Reset_password_confirmation {
            get {
                return ResourceManager.GetString("Reset password confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        public static string Reset_recovery_codes {
            get {
                return ResourceManager.GetString("Reset recovery codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        public static string reset_your_authenticator_keys_ {
            get {
                return ResourceManager.GetString("reset your authenticator keys.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string Reset_your_password_ {
            get {
                return ResourceManager.GetString("Reset your password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code or enter this key.
        /// </summary>
        public static string Scan_the_QR_Code_or_enter_this_key {
            get {
                return ResourceManager.GetString("Scan the QR Code or enter this key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        public static string Send_verification_email {
            get {
                return ResourceManager.GetString("Send verification email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Set_password {
            get {
                return ResourceManager.GetString("Set password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your password.
        /// </summary>
        public static string Set_your_password {
            get {
                return ResourceManager.GetString("Set your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup authenticator app.
        /// </summary>
        public static string Setup_authenticator_app {
            get {
                return ResourceManager.GetString("Setup authenticator app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapping to.
        /// </summary>
        public static string Swapping_to {
            get {
                return ResourceManager.GetString("Swapping to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See.
        /// </summary>
        public static string There_are_no_external_authentication_services_configured__See {
            get {
                return ResourceManager.GetString("There are no external authentication services configured. See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to these docs.
        /// </summary>
        public static string these_docs {
            get {
                return ResourceManager.GetString("these docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string This_account_has_been_locked_out__please_try_again_later_ {
            get {
                return ResourceManager.GetString("This account has been locked out, please try again later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        public static string This_action_only_disables_2FA_ {
            get {
                return ResourceManager.GetString("This action only disables 2FA.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app does not currently have a real email sender registered, see.
        /// </summary>
        public static string This_app_does_not_currently_have_a_real_email_sender_registered__see {
            get {
                return ResourceManager.GetString("This app does not currently have a real email sender registered, see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this article.
        /// </summary>
        public static string this_article {
            get {
                return ResourceManager.GetString("this article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process disables 2FA until you verify your authenticator app. If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        public static string This_process_disables_2FA_until_you_verify_your_authenticator_app__If_you_do_not_complete_your_authenticator_app_configuration_you_may_lose_access_to_your_account_ {
            get {
                return ResourceManager.GetString("This process disables 2FA until you verify your authenticator app. If you do not " +
                        "complete your authenticator app configuration you may lose access to your accoun" +
                        "t.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps:.
        /// </summary>
        public static string To_use_an_authenticator_app_go_through_the_following_steps_ {
            get {
                return ResourceManager.GetString("To use an authenticator app go through the following steps:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string Two_factor_authentication {
            get {
                return ResourceManager.GetString("Two-factor authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication (2FA).
        /// </summary>
        public static string Two_factor_authentication__2FA_ {
            get {
                return ResourceManager.GetString("Two-factor authentication (2FA)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string Update_password {
            get {
                return ResourceManager.GetString("Update password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string Use_a_local_account_to_log_in_ {
            get {
                return ResourceManager.GetString("Use a local account to log in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string Use_another_service_to_log_in_ {
            get {
                return ResourceManager.GetString("Use another service to log in.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to register..
        /// </summary>
        public static string Use_another_service_to_register_ {
            get {
                return ResourceManager.GetString("Use another service to register.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to detail your site&apos;s privacy policy..
        /// </summary>
        public static string Use_this_page_to_detail_your_site_s_privacy_policy_ {
            get {
                return ResourceManager.GetString("Use this page to detail your site\'s privacy policy.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string Verification_Code {
            get {
                return ResourceManager.GetString("Verification Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can.
        /// </summary>
        public static string You_can {
            get {
                return ResourceManager.GetString("You can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string You_do_not_have_a_local_username_password_for_this_site__Add_a_local_account_so_you_can_log_in_without_an_external_login_ {
            get {
                return ResourceManager.GetString("You do not have a local username/password for this site. Add a local account so y" +
                        "ou can log in without an external login.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string You_do_not_have_access_to_this_resource_ {
            get {
                return ResourceManager.GetString("You do not have access to this resource.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 recovery code left..
        /// </summary>
        public static string You_have_1_recovery_code_left_ {
            get {
                return ResourceManager.GetString("You have 1 recovery code left.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        public static string You_have_no_recovery_codes_left_ {
            get {
                return ResourceManager.GetString("You have no recovery codes left.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to log in with a recovery code. This login will not be remembered until you provide an authenticator app code at log in or disable 2FA and log in again..
        /// </summary>
        public static string You_have_requested_to_log_in_with_a_recovery_code__This_login_will_not_be_remembered_until_you_provide_an_authenticator_app_code_at_log_in_or_disable_2FA_and_log_in_again_ {
            get {
                return ResourceManager.GetString("You have requested to log in with a recovery code. This login will not be remembe" +
                        "red until you provide an authenticator app code at log in or disable 2FA and log" +
                        " in again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out of the application..
        /// </summary>
        public static string You_have_successfully_logged_out_of_the_application_ {
            get {
                return ResourceManager.GetString("You have successfully logged out of the application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must.
        /// </summary>
        public static string You_must {
            get {
                return ResourceManager.GetString("You must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should.
        /// </summary>
        public static string You_should {
            get {
                return ResourceManager.GetString("You should", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string You_ve_successfully_authenticated_with {
            get {
                return ResourceManager.GetString("You\'ve successfully authenticated with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        public static string Your_account_contains_personal_data_that_you_have_given_us__This_page_allows_you_to_download_or_delete_that_data_ {
            get {
                return ResourceManager.GetString("Your account contains personal data that you have given us. This page allows you " +
                        "to download or delete that data.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app. Enter your authenticator code below..
        /// </summary>
        public static string Your_login_is_protected_with_an_authenticator_app__Enter_your_authenticator_code_below_ {
            get {
                return ResourceManager.GetString("Your login is protected with an authenticator app. Enter your authenticator code " +
                        "below.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string Your_password_has_been_reset__Please {
            get {
                return ResourceManager.GetString("Your password has been reset. Please", resourceCulture);
            }
        }
    }
}
